### ISSUE TITLE
NotImplementedError on Windows with Python 3.8

### ISSUE THREAD

**Issue by acwoerl** [lukeparser/lukeparser#52]
Livereload does not work on Windows with Python 3.8. Reason for this error is described in the following [link](https://github.com/tornadoweb/tornado/pull/2686/files)

**Comment by da-h** [comment]
Hi *BlubKeks*,

thank you very much for your feedback!

I have included tornados code recommendations into the main loop of the lukeparser server.
Could you please verify if `luke --live` works with the newest version?

Best
*da-h*

**Comment by acwoerl** [comment]
Hey da-h,

I checked it. Now there is a NameError. Maybe you forgot to import sys? Thanks for the quick reply 👍

**Comment by da-h** [comment]
You are totally right!
I pushed the change, version `0.3.8.6` should appear soon on pip.

**Comment by da-h** [comment]
b79d75540f301b1bdbc9ba4d6c29cc7bf2a47f91

**Comment by acwoerl** [comment]
Okay, next problem ;-) you cannot check, whether sys.version_info is larger than a float. You can use 
`sys.version >= "3.8"` instead, i tested it

**Comment by da-h** [comment]
It was just a typo, sorry. You can compare the version with a tuple. (aab6364)

Thank you for your help & please let me know, if it works now on windows. :)

**Comment by acwoerl** [comment]
Hey _da-h_,

works perfectly under windows now (:
