### ISSUE TITLE
References in included files do not work

### ISSUE THREAD

**Issue by f-fr** [lukeparser/lukeparser#61]
Consider the following two files in the same directory:

test.md:
```
\include{"./other.md"}
```

other.md:
```
![Foo][^ref] baz

[^ref]: bar
```
Showing the file "test.md" raises an error:

```
...
ValueError: Variable content not found in Object of type note
```

**Comment by da-h** [comment]
Thank you for your comment and please excuse the late response.
This is indeed a bug. I just added a new version, `v0.3.18`, that should fix this.

Could you please cross-check the against the new version?

In this version, the file should actually place the file at the specified position as if the content was placed in the source file. Thus, the new version allows the `other.md` file to contain, for instance, only footnotes that are used inside of the main file `test.md`.

`other.md`:
```
[^ref1]: bar 1
[^ref2]: bar 2
[^ref3]: bar 3
```

`test.md`
```
\include{"./other.md"}

[Foo1][^ref1] baz
[Foo2][^ref2] baz
[Foo3][^ref3] baz
```

**Comment by f-fr** [comment]
Seems to work. Thanks.
