### ISSUE TITLE
Add support to release linux aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [lukeparser/lukeparser#64]
Problem
---------
On aarch64, `pip install lukeparser` builds the wheels from source code and then installs it. It requires the user to have a development environment installed on their system. Also, it takes more time to build the wheels than downloading and extracting the wheels from PyPI.

Resolution
-----------
On aarch64, `pip install lukeparser` should download the wheels from PyPI.

@sbrodehl, Please let me know your interest in releasing aarch64 wheels. I can help with this.

**Comment by sbrodehl** [comment]
Hi @odidev,

thanks for bringing this up! I think it is a great addition to the project, will review the PR as soon as possible!
